const evidence: Record<string, { method: string; limitation: string; keys: string[] }> = {
  spine_coverage: { method: 'Классификация укладки по изображению и геометрическим признакам.', limitation: 'Половина Th12 не локализуется отдельно; этот ориентир автоматически не подтверждён.', keys: [] },
  spine_axis: { method: 'Оценка оси по геометрии изображения; критерий ТЗ — наклон до 5°.', limitation: 'В решении версии 3 критерий определяется измеренным углом: больше 5°. Точность локализации оси требует независимой проверки.', keys: ['axis', 'centerline'] },
  spine_artifact: { method: 'Классификация наличия посторонних предметов и артефактов.', limitation: 'Точная маска обнаруженного предмета не выдаётся.', keys: [] },
  hip_position_rotation: { method: 'Классификация позиционирования и ротации бедра.', limitation: 'Наличие всех требуемых анатомических ориентиров не подтверждено отдельным локализатором.', keys: ['shaft_axis', 'lesser_trochanter'] },
  hip_roi_coverage: { method: 'Классификация охвата кадра с геометрическими признаками.', limitation: 'Это не измерение отступов от нанесённой ROI. Выбранный полигон проверяется отдельно в разделе «Отступы ROI».', keys: [] },
}
export default function CriteriaPanel({ codes, labels, scores, detected, angle, onShow }: { codes: string[]; labels: Record<string, string>; scores: Record<string, number>; detected: string[]; angle: number | null; onShow: (keys: string[]) => void }) {
  return <section aria-label="Основания по критериям"><h3>Основания по критериям ТЗ</h3>{codes.map(code => <article key={code}><h4>{labels[code] || code}</h4><p>{Number.isFinite(scores[code]) ? detected.includes(code) ? 'Включено в итоговые нарушения модели.' : 'Не включено в итоговые нарушения модели.' : 'Критерий не оценён.'}</p><p>{evidence[code]?.method}</p><p>{evidence[code]?.limitation || 'Отдельное объяснение критерия отсутствует.'}</p>{code === 'spine_axis' && <p>Измеренный наклон: {angle !== null && Number.isFinite(angle) ? `${angle.toFixed(2)}°` : 'недоступен'}.</p>}{evidence[code]?.keys.length > 0 && <button onClick={() => onShow(evidence[code].keys)}>Показать ориентиры: {labels[code] || code}</button>}</article>)}</section>
}
